URECA-TEAM-5/PopFlix-frontend

src/components/Login/LoginModal.jsx, src/route/RouteDef.jsx
=> style: 로그인 모달 디자인(버튼 미구현)

src/components/Login/LoginModal.jsx, src/components/userInfo/UserInfoGender.jsx, src/components/userInfo/UserInfoGenre.jsx, src/components/userInfo/UserInfoImage.jsx, src/components/userInfo/UserInfoNickname.jsx, src/pages/addUserInfo/AddUserInfo.jsx, src/route/RouteDef.jsx
=> fix: CT-901 오류 해결을 위한 새 브랜치 생성

src/components/mypage/UserProfile.jsx, src/pages/mypage/Mypage.jsx
=> style: MyPage UserProfile 디자인

src/components/Login/LoginModal.jsx, src/components/userInfo/UserInfoImage.jsx
=> fix: 아이콘 경로 수정

src/api/axios.js
=> feat: 토큰 관리

src/api/auth/auth.js, src/api/axios.js, src/components/userInfo/UserInfoGender.jsx, src/components/userInfo/UserInfoImage.jsx, src/pages/userInfo/AddUserInfo.jsx
=> feat:회원가입 연동 및 토큰관리 수정

src/api/axios.js
=> feat: 토큰관리 수정

src/api/axios.js, src/components/common/header/HeaderIconSection.jsx, src/components/userInfo/modal/MyInfoModal.jsx, src/pages/welcome/Welcome.jsx, src/route/RouteDef.jsx
=> feat:localSotrage에 데이터 저장 및 로그인 완료 관련 페이지

src/api/watchlist/watchlist.js, src/components/myWatchlistModal/NewFolderModal.jsx, src/components/mypage/MyFavoriteWatchList.jsx, src/components/mypage/MyWatchList.jsx, src/components/watchlistEdit/EditMovieList.jsx, src/components/watchlistEdit/EditStorage.jsx
=> refactor: userId 로컬스토리지 사용

src/api/watchlist/watchlist.js, src/components/watchlist/WatchListMonth.jsx
=> fix: 이달의 인기 watchlist api 반영

src/components/common/header/Header.jsx, src/components/userInfo/modal/MyInfoModal.jsx, src/pages/welcome/Welcome.jsx
=> fix: 토큰 관리 welcome 페이지 수정

src/components/userInfo/modal/MyInfoModal.jsx
=> fix: 로그아웃 기능 수정

src/api/axios.js, src/components/common/header/HeaderIconSection.jsx, src/components/mypage/UserProfile.jsx, src/components/userInfo/modal/MyInfoModal.jsx, src/pages/userInfo/AddUserInfo.jsx, src/pages/welcome/Welcome.jsx
=> feat: 로그인 했을때 사용자 이미지 및 Sotrage 변경

src/components/mypage/MyWatchList.jsx, src/components/watchlistEdit/EditStorage.jsx
=> style: 마이페이지 snackbar 추가

src/api/mypage/myWatchList.js, src/components/myWatchlistModal/NewFolderInput.jsx, src/components/myWatchlistModal/NewFolderModal.jsx, src/components/mypage/MyFavoriteWatchList.jsx, src/components/mypage/MyWatchList.jsx, src/components/mypage/style/MyFavoriteWatchList.js, src/components/mypage/style/MyWatchList.js, src/components/watchlist/WatchListMonth.jsx, src/components/watchlist/style/WatchListMonth.js, src/components/watchlistEdit/EditMovieList.jsx, src/components/watchlistEdit/EditStorage.jsx, src/components/watchlistEdit/style/EditMoviList.js, src/components/watchlistEdit/style/EditStorage.js, src/pages/watchlist/style/WatchListPage.js
=> style: watchlist 공용 컴포넌트 적용 및 수정 페이지 UI 변경

src/api/auth/auth.js, src/components/mypage/UserProfile.jsx, src/components/userInfo/modal/WithdrawalModal.jsx, src/components/userInfo/style/UserInfoStyle.js, src/pages/userInfo/AddUserInfo.jsx, src/pages/userInfo/UpdateUserInfo.jsx
=> feat:회원정보 수정 및 회원탈퇴 그외 오류 수정

src/api/auth/auth.js, src/api/axios.js, src/components/mypage/MyWatchList.jsx, src/components/mypage/UserProfile.jsx, src/components/userInfo/UserInfoImage.jsx, src/components/userInfo/UserInfoNickname.jsx, src/components/userInfo/modal/DefaultImageSelectModal.jsx, src/components/userInfo/modal/ImageSelectModal.jsx, src/components/userInfo/modal/MyInfoModal.jsx, src/pages/userInfo/AddUserInfo.jsx, src/pages/userInfo/UpdateUserInfo.jsx, src/pages/welcome/Welcome.jsx
=> refactor: 코드 수정 및 정리

src/components/common/header/Header.jsx
=> delete: 리뷰왕 제거

src/api/auth/auth.js, src/api/axios.js, src/components/mypage/UserProfile.jsx, src/components/userInfo/UserInfoImage.jsx, src/pages/userInfo/UpdateUserInfo.jsx, src/pages/welcome/Welcome.jsx
=> delete: 주석 제거

src/pages/welcome/Welcome.jsx
=> refactor: 경로 이동 빠진거 추가

src/components/watchlistDetail/WatchListDetailOtherStorage.jsx, src/components/watchlistDetail/style/WatchListDetailMovieList.js, src/components/watchlistDetail/style/WatchListDetailOtherStorage.js
=> fix: 다른 보관함 목록 UI 수정

src/components/myWatchlistModal/NewFolderModal.jsx, src/components/mypage/MyWatchList.jsx, src/pages/mypage/Mypage.jsx
=> fix: Snackbar 겹침 현상 수정
